rs/urls.py
from django.conf.urls import url

from rs.views import *

urlpatterns = [
    url(r'^movie/(?P<movie_id>\d+)/vote', VoteView.as_view(), name='vote'),
    url(r'^user/votes', VoteListView.as_view(), name='vote_list'),
]

tmdb/urls.py
from django.conf.urls import url
from tmdb.views import *

urlpatterns = [
    url(r'^$', HomePageView.as_view(),
        name='home'),
    url(r'^movie/(?P<pk>\d+)/$', MovieDetailView.as_view(),
        name='movie'),
    url(r'^movies/$', MovieListView.as_view()),
    url(r'^movies/page/(?P<page>\d+)/$', MovieListView.as_view(),
        name='movie_list'),
    # watchlist action
    url(r'^movie/(?P<movie_id>\d+)/watchlist_action', WatchlistView.as_view(), name='watchlist_action'),
    url(r'^user/watchlist', WatchlistListView.as_view(), name='watchlist'),
    # blacklist action
    url(r'^movie/(?P<movie_id>\d+)/blacklist_action', BlacklistView.as_view(), name='blacklist_action'),
    url(r'^user/blacklist', BlacklistListView.as_view(), name='blacklist'),
]

tmdb/models.py
"""TMDb Application Models

class Movie(models.Model) - main structural unit of TMDb's representation
and start point of module. Other models depends on Movie.
"""
from django.db import models
from django.db.models import Q
from select2 import fields
from django.contrib.auth.models import User


class Character(models.Model):
    """
    Stores information about movie characters and actor they are performed by
    """
    movie = models.ForeignKey('Movie', on_delete=models.CASCADE, default=None)
    character = models.TextField(null=True, blank=True)
    actor = models.TextField()

    # Proposes special order of characters within a movie
    order = models.IntegerField()

    picture = models.TextField(null=True, blank=True)

    def __str__(self):
        return '%s (%s)' % (self.actor, self.character)


class Company(models.Model):
    """
    Information about the company that produced the movie
    """
    id = models.IntegerField(primary_key=True)
    name = models.TextField()

    def __str__(self):
        return self.name


class Country(models.Model):
    """
    Information about country, in which the movie was produced
    """

    # ISO country code
    # from ISO 3166-1 - Codes for the representation of names
    # of countries and their subdivisions – Part 1: Country codes
    # More: https://en.wikipedia.org/wiki/ISO_3166-1
    code = models.CharField(primary_key=True, max_length=6)

    # Name of country in English
    name = models.TextField()

    def __str__(self):
        return "%s (%s)" % (self.name, self.code)


class Genre(models.Model):
    """
    Stores information about genre of movie
    """
    id = models.IntegerField(primary_key=True)
    name = models.TextField()

    def __str__(self):
        return self.name


class Keyword(models.Model):
    """
    Stores word for movie search
    """
    id = models.IntegerField(primary_key=True)
    name = models.TextField()  # as like as in Genre

    def __str__(self):
        return self.name


class Movie(models.Model):
    """
    Information about movie. Main structural unit
    """
    id = models.IntegerField(primary_key=True)

    # General
    title = models.TextField()
    original_title = models.TextField()
    original_language = models.TextField()
    release_date = models.DateField(null=True, blank=True)
    overview_en = models.TextField(null=True, blank=True)
    runtime = models.IntegerField(null=True, blank=True)

    # Creators
    companies = fields.ManyToManyField(
        Company,
        ajax=True,
        search_field=lambda q: Q(name__icontains=q),
        js_options={'quiet_millis': 200}
    )
    countries = fields.ManyToManyField(
        Country,
        ajax=True,
        search_field=lambda q: Q(name__icontains=q),
        js_options={'quiet_millis': 200}
    )

    # Financial info
    budget = models.FloatField(null=True, blank=True)
    revenue = models.FloatField(null=True, blank=True)

    # Websites
    homepage = models.TextField(null=True, blank=True)
    imdb_id = models.CharField(max_length=10, null=True, blank=True)

    # Categorization
    genres = fields.ManyToManyField(
        Genre,
        ajax=True,
        search_field='name',
        js_options={'quiet_millis': 200}
    )
    keywords = fields.ManyToManyField(
        Keyword,
        ajax=True,
        search_field=lambda q: Q(name__icontains=q),
        js_options={'quiet_millis': 200}
    )

    # User votes (dumped from TMDb)
    vote_count = models.IntegerField()
    vote_average = models.FloatField()

    # Unique views on the TMDb website but improved with taking in
    # account the number of ratings a movie received, number of favourites
    # and number of watched list additions all for the previous day.
    # It also uses the part of the previous days score to help popularity
    # trending and finally, boosts scores a tad if the newer a release date is.
    popularity = models.FloatField()

    # Media
    poster_path = models.TextField(null=True, blank=True)
    backdrop_path = models.TextField(null=True, blank=True)

    # Special marks
    adult = models.BooleanField()

    # Current status of the movie (one of following):
    # - Released
    # - In Production
    # - Planned
    # - Post Production
    # - Rumored/Canceled
    status = models.TextField()

    # Recommendation System (RS) fields
    # ... goes here

    def __str__(self):
        return "%s (%d)" % (self.title, self.release_date.year)

    @property
    def get_trailer(self):
        """
        Returns main trailer video for movie.
        :return: object of models.Video or None, if it absent
        """
        trailers = self.video_set.filter(type='Trailer')
        if len(trailers) > 0:
            return trailers[0]

    def get_trailer_list(self):
        """
        Shortcut for list of trailers for this movie
        :return: QuerySet of models.Video
        """
        return self.video_set.filter(type='Trailer')


class Video(models.Model):
    """
    Stores link on trailer or film.
    """
    id = models.CharField(primary_key=True, max_length=200)

    # Relation with the model of the film that describes
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, default=None)

    # Unique ID of video file or page at external website
    key = models.CharField(max_length=200, null=True, blank=True)

    name = models.TextField()

    # Name of site where video is stored
    site = models.TextField()

    # Video quality in pixels of height
    size = models.IntegerField()

    # Type of video. One of following:
    # - Trailer
    type = models.TextField()

    def __str__(self):
        return '%s (%s)' % (self.name, self.type)

class Watchlist(models.Model):
    """
    Saves movies to user watchlist
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return '%s (%s)' \
               % (self.movie.title, self.user.username)

tmdb/views.py
import random

import datetime
from django.db.models import F, ExpressionWrapper, DecimalField
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from django.views import View
from django.shortcuts import redirect

from rs.models import Vote
from rs.recommenders import UserBased, ContentBased
from tmdb.models import *


class HomePageView(TemplateView):
    template_name = "tmdb/home.jinja2"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['user_based_recommendations'] = UserBased().get(self.request.user) \
                                                        .filter(vote_average__gt=4)[:100]
            start_pos = random.randint(0, len(context['user_based_recommendations']) - 6)
            context['user_based_recommendations'] = context['user_based_recommendations'][start_pos:start_pos+6]
            user_based_ids = []
            for movie in context['user_based_recommendations']:
                user_based_ids += [movie.id]
            context['content_based_recommendations'] = ContentBased().get(self.request.user) \
                                                           .filter(vote_average__gt=4) \
                                                           .exclude(id__in=user_based_ids)[:100]
            # start_pos = random.randint(0, len(context['content_based_recommendations']) - 6)
            start_pos = random.randint(0, len(context['content_based_recommendations']) - 6) if len(context['content_based_recommendations']) > 0 else 0

            context['content_based_recommendations'] = context['content_based_recommendations'][start_pos:start_pos+6]
        context['popular_movies'] = Movie.objects \
            .prefetch_related('genres').annotate(
            order_value=ExpressionWrapper(F('vote_average') - 1000 / F('vote_count'), output_field=DecimalField())) \
            .order_by('-order_value')[:100]
      #  start_pos = random.randint(0, len(context['popular_movies']) - 6)
        start_pos = random.randint(0, len(context['popular_movies']) - 6) if len(context['popular_movies']) > 0 else 0
        context['popular_movies'] = context['popular_movies'][start_pos:start_pos+12]
        return context


class MovieListView(ListView):
    model = Movie
    template_name = 'tmdb/movie_list.jinja2'
    paginate_by = 36

    def get_queryset(self):
        blocked = Vote.objects.filter(
                user=self.request.user,
                value = 0
            ).values('movie_id')
        return super(MovieListView, self).get_queryset() \
            .prefetch_related('genres').annotate(
            order_value=ExpressionWrapper(F('vote_average') - 1000 / F('vote_count'), output_field=DecimalField())) \
            .order_by('-order_value').exclude(id__in=blocked)

    def get_context_data(self, **kwargs):
        context = super(MovieListView, self).get_context_data(**kwargs)
        if not self.request.user.is_authenticated():
            return context

        context['vote_dict'] = {}
        for movie in context['object_list']:
            try:
                context['vote_dict'][movie.pk] = Vote.objects.get(
                    user=self.request.user,
                    movie=movie
                ).value
            except Vote.DoesNotExist:
                pass

        return context


class MovieDetailView(DetailView):
    model = Movie
    template_name = 'tmdb/movie.jinja2'
    context_object_name = 'movie'

    def get_queryset(self):
        return super(MovieDetailView, self).get_queryset() \
            .prefetch_related('genres', 'companies')

    def get_context_data(self, **kwargs):
        context = super(MovieDetailView, self).get_context_data(**kwargs)
        if not self.request.user.is_authenticated():
            return context

        try:
            context['vote'] = Vote.objects.get(
                user=self.request.user,
                movie=context['movie']
            ).value
        except Vote.DoesNotExist:
            pass

        try:
            context['in_watchlist'] = Watchlist.objects.get(
                user=self.request.user,
                movie=context['movie']
            )
        except Watchlist.DoesNotExist:
            pass

        try:
            context['in_blacklist'] = Vote.objects.filter(
                user=self.request.user,
                movie__id=context['movie'].id,
                value = 0
            )
        except Watchlist.DoesNotExist:
            pass

        return context


class WatchlistView(View):
    def post(self, request, movie_id):
        try:
            object = Watchlist.objects.get(
                user=request.user,
                movie__id=movie_id
            )
            Watchlist.objects.filter(
                user=request.user,
                movie__id=movie_id,
            ).delete()
            if request.is_ajax():
                return HttpResponse('removed')

        except Watchlist.DoesNotExist:
            created = Watchlist.objects.update_or_create(
                user=request.user,
                movie__id=movie_id,
                defaults={
                    'movie_id': movie_id,
                },
            )
            if request.is_ajax():
                return HttpResponse('added')
            pass

        nxt = request.POST.get('next', '')
        if not nxt:
            nxt = request.META.get('HTTP_REFERER')

        return redirect(nxt)


class WatchlistListView(ListView):
    model = Watchlist
    template_name = 'tmdb/watchlist.jinja2'

    def get_queryset(self):
        blocked = Vote.objects.filter(
                user=self.request.user,
                value = 0
            ).values('movie_id')
        return super(WatchlistListView, self).get_queryset() \
            .filter(user=self.request.user) \
            .exclude(movie_id__in=blocked)

class BlacklistView(View):
    def post(self, request, movie_id):
        try:
            object = Vote.objects.get(
                user = request.user,
                movie__id=movie_id
            )
            if object.value != 0:
                Vote.objects.update_or_create(
                    user=request.user,
                    movie__id=movie_id,
                    defaults={
                        'movie_id': movie_id,
                        'value': 0,
                    },
                )
                if request.is_ajax():
                    return HttpResponse('blocked')
            else:
                Vote.objects.filter(
                    user=request.user,
                    movie__id=movie_id,
                ).delete()
            if request.is_ajax():
                return HttpResponse('unblocked')

        except Vote.DoesNotExist:
            Vote.objects.update_or_create(
                user=request.user,
                movie__id=movie_id,
                defaults={
                    'movie_id': movie_id,
                    'value': 0,
                },
            )
            if request.is_ajax():
                return HttpResponse('created and blocked')
            pass

        nxt = request.POST.get('next', '')
        if not nxt:
            nxt = request.META.get('HTTP_REFERER')

        return redirect(nxt)

class BlacklistListView(ListView):
    model = Movie
    template_name = 'tmdb/blacklist.jinja2'
    paginate_by = 36

    def get_queryset(self):
        blocked = Vote.objects.filter(
            user=self.request.user,
            value=0
        ).values('movie_id')

        return super(BlacklistListView, self).get_queryset() \
            .filter(id__in=blocked)

templates/tmdb/blacklist.jinja2
{% extends "layouts/application.jinja2" %}

{% block content %}
  {% for movie in object_list %}

    <div class="pure-g">
      <div class="pure-u-1-4 box photo-box">
        <a href="{{ url_for('movie', movie.pk) }}">
          <img src="https://image.tmdb.org/t/p/w342{{ movie.poster_path }}"
               alt="{{ movie.title }}">
        </a>
      </div>

      <div class="pure-u-3-4 box">
        <h4>
          <a href="{{ url_for('movie', movie.pk) }}">{{ movie.title }}</a>
          <br>
          <small style="font-style: italic;">{{ movie.original_title }}</small>
        </h4>

        <p>{{ movie.overview_en }}</p>

      </div>
    </div>
  {% endfor %}
{% endblock %}

templates/tmdb/home.jinja2
{% extends "layouts/milligram.jinja2" %}

{% from "macros/votes.jinja2" import vote_form with context %}

{% block content %}
  <div class="page-main">
    <div class="container">
      {% if user_based_recommendations or content_based_recommendations %}
      <h2>We recommend</h2>
      <div class="row row-wrap row-stretch movie-list">
        {% for movie in user_based_recommendations %}
          <div class="column column-25">
            <section class="movie-card">
              <div class="movie-card-picture">
                <a href="{{ url_for('movie', movie.pk) }}">
                  <img srcset="{{ tmdb_image(movie.backdrop_path, 'set') }}"
                       src="{{ tmdb_image(movie.backdrop_path, 'w500') }}"
                       alt="{{ movie.title }}">
                </a>
              </div>

              <h3 class="movie-card-title">
                <a href="{{ url_for('movie', movie.pk) }}">
                  {{ movie.title }}
                </a>
              </h3>

              <ul class="movie-card-details">
                {%- if movie.release_date %}
                  <li>{{ movie.release_date.year }}</li>
                {% endif %}

                <li>
                  {{ movie.genres.all()|join(', ') }}
                </li>

                <li class="movie-card-vote-number">
                  {{ movie.vote_average }}
                </li>
              </ul>
            </section>
          </div>
        {% endfor %}
        {% for movie in content_based_recommendations %}
          <div class="column column-25">
            <section class="movie-card">
              <div class="movie-card-picture">
                <a href="{{ url_for('movie', movie.pk) }}">
                  <img srcset="{{ tmdb_image(movie.backdrop_path, 'set') }}"
                       src="{{ tmdb_image(movie.backdrop_path, 'w500') }}"
                       alt="{{ movie.title }}">
                </a>
              </div>

              <h3 class="movie-card-title">
                <a href="{{ url_for('movie', movie.pk) }}">
                  {{ movie.title }}
                </a>
              </h3>

              <ul class="movie-card-details">
                {%- if movie.release_date %}
                  <li>{{ movie.release_date.year }}</li>
                {% endif %}

                <li>
                  {{ movie.genres.all()|join(', ') }}
                </li>

                <li class="movie-card-vote-number">
                  {{ movie.vote_average }}
                </li>
              </ul>
            </section>
          </div>
        {% endfor %}
      </div>
      {% endif %}
      <h2>Popular</h2>
      <div class="row row-wrap row-stretch movie-list">
        {% for movie in popular_movies %}
          <div class="column column-25">
            <section class="movie-card">
              <div class="movie-card-picture">
                <a href="{{ url_for('movie', movie.pk) }}">
                  <img srcset="{{ tmdb_image(movie.backdrop_path, 'set') }}"
                       src="{{ tmdb_image(movie.backdrop_path, 'w500') }}"
                       alt="{{ movie.title }}">
                </a>
              </div>

              <h3 class="movie-card-title">
                <a href="{{ url_for('movie', movie.pk) }}">
                  {{ movie.title }}
                </a>
              </h3>

              <ul class="movie-card-details">
                {%- if movie.release_date %}
                  <li>{{ movie.release_date.year }}</li>
                {% endif %}

                <li>
                  {{ movie.genres.all()|join(', ') }}
                </li>

                <li class="movie-card-vote-number">
                  {{ movie.vote_average }}
                </li>
              </ul>
            </section>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

templates/tmdb/movie.jinja2
{% extends "layouts/milligram.jinja2" %}

{% from "macros/votes.jinja2" import vote_form with context %}
{% from "macros/watchlist-action.jinja2" import watchlist_action_form with context %}
{% from "macros/blacklist-action.jinja2" import blacklist_action_form with context %}

{% block content %}
  <article class="movie">
    <div class="movie-hero"
         style="background-image: url({{ tmdb_image(movie.backdrop_path) }});">
      <div class="container">
        <div class="row">
          <div class="column column-25">
            <img src="{{ tmdb_image(movie.poster_path, 'w500') }}"
                 alt="{{ movie.title }}"
                 class="movie-poster">
          </div>

          <div class="column column-75">
            <header class="movie-header">
              <h1 class="movie-title">
                {{ movie.title }}
              </h1>
            </header>

            <section id="overview">
              {%- if request.user.is_authenticated() %}
                <div class="row">
                  {{ blacklist_action_form(movie, in_blacklist) }}
                  <div class="column column-67">
                    {{ vote_form(movie, vote) }}
                  </div>
                  <div class="column column-33 text-right">
                    <strong>{{ movie.vote_average }}</strong>
                    by {{ movie.vote_count }}
                    vote{{ movie.vote_count|pluralize }}
                  </div>
                </div>
              {% else %}
                <div>
                  <strong>{{ movie.vote_average }}</strong>
                  by {{ movie.vote_count }} vote{{ movie.vote_count|pluralize }}
                </div>
              {% endif %}

              {% if movie.overview_en %}
                <p class="movie-overview">{{ movie.overview_en }}</p>
              {% endif %}

              <div class="movie-actions">
                {% set trailer = movie.get_trailer %}
                {% if trailer %}
                  <a href="{{ video_url(trailer) }}"
                     data-site="{{ trailer.site }}" data-key="{{ trailer.key }}"
                     class="button movie-trailer-link">
                    Watch trailer
                  </a>
                {% endif %}
                {%- if request.user.is_authenticated() %}
                    {{ watchlist_action_form(movie, in_watchlist) }}
                {% endif %}
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>

    <div class="movie-content">
      <div class="container">
        <div class="row">
          <div class="column column-75 movie-main">
            {% set characters = movie.character_set.all().order_by('order') %}
            {% if characters.count() > 0 %}
              <section class="movie-section" id="cast">
                <h2>Cast</h2>

                <div class="row movie-actor-list">
                  {% for character in characters %}
                    <div class="column column-33 movie-actor">
                      <div class="movie-actor-picture">
                        {% if character.picture %}
                        <img src="{{ tmdb_image(character.picture, 'w300') }}"
                             alt="{{ character.actor }}">
                        {% else %}
                        <img src="{{ static('images/actor-placeholder-0%d.png' | format(range(1, 4) | random)) }}"
                             alt="{{ character.actor }}">
                        {% endif %}
                      </div>

                      <h5 class="movie-actor-name">
                        {{ character.actor }}
                      </h5>

                      <p class="movie-actor-role">
                        {{ character.character }}
                      </p>
                    </div>
                  {% endfor %}
                </div>
              </section>
            {% endif %}

            {#{% set videos # movie.video_set.all() %}#}
            {% if false %}
              <section class="movie-section" id="videos">
                <h2>Videos</h2>

                <div class="row movie-video-list">
                  {% for video in videos %}
                    <div class="column column-33">
                      {{ video }}
                    </div>
                  {% endfor %}
                </div>
              </section>
            {% endif %}
          </div>

          <div class="column column-25 movie-sidebar">
            <section class="movie-section" id="stats">
              <h2>Facts</h2>

              <dl class="movie-facts">
                <dt>Status</dt>
                <dd>{{ movie.status|capitalize }}</dd>

                {% if movie.release_date %}
                  <dt>Release information</dt>
                  <dd>{{ movie.release_date.strftime('%B %d, %Y') }}</dd>
                {% endif %}

                <dt>Original language</dt>
                <dd>{{ movie.original_language|capitalize }}</dd>

                {% if movie.runtime %}
                  <dt>Runtime</dt>
                  <dd>{{ '%dh %dm'|format(
                    movie.runtime / 60,
                    movie.runtime % 60
                  ) }}</dd>
                {% endif %}

                {% if movie.budget %}
                  <dt>Budget</dt>
                  <dd>{{ '$&nbsp;{:,}'
                    .format(movie.budget|int)
                    .replace(',', '&nbsp;') | safe }}</dd>
                {% endif %}

                {% if movie.revenue %}
                  <dt>Revenue</dt>
                  <dd>{{ '$&nbsp;{:,}'
                    .format(movie.revenue|int)
                    .replace(',', '&nbsp;') | safe }}</dd>
                {% endif %}

                {% if movie.homepage %}
                  <dt>Homepage</dt>
                  <dd>
                    <a href="{{ movie.homepage }}">{{ movie.homepage }}</a>
                  </dd>
                {% endif %}

                {% if movie.adult %}
                  <dt>Restrictions</dt>
                  <dd>Adult movie, <strong>18+</strong></dd>
                {% endif %}
              </dl>
            </section>

            <section class="movie-section" id="genres">
              <h2>Genres</h2>

              <ul class="movie-genres">
                {% for genre in movie.genres.values() %}
                  <li>{{ genre.name }}</li>
                {% endfor %}
              </ul>
            </section>

            <section class="movie-section">
              <h2>Keywords</h2>

              <ul class="movie-keywords">
                {% for keyword in movie.keywords.values() %}
                  <li>{{ keyword.name }}</li>
                {% endfor %}
              </ul>
            </section>
          </div>
        </div>
      </div>
    </div>
  </article>
{% endblock %}

{% block scripts %}
  <div class="modal movie-modal"></div>
  <script src="{{ static('js/trailer.js') }}"></script>
{% endblock %}

templates/tmdb/movie_list.jinja2
{% extends "layouts/milligram.jinja2" %}

{% from "macros/votes.jinja2" import vote_form with context %}

{% block content %}
  <div class="page-main">
    <div class="container">
      <div class="row row-wrap row-stretch movie-list">
        {% for movie in object_list %}
          <div class="column column-25">
            <section class="movie-card">
              <div class="movie-card-picture">
                <a href="{{ url_for('movie', movie.pk) }}">
                  <img srcset="{{ tmdb_image(movie.backdrop_path, 'set') }}"
                       src="{{ tmdb_image(movie.backdrop_path, 'w500') }}"
                       alt="{{ movie.title }}">
                </a>
              </div>

              <h3 class="movie-card-title">
                <a href="{{ url_for('movie', movie.pk) }}">
                  {{ movie.title }}
                </a>
              </h3>

              <ul class="movie-card-details">
                {%- if movie.release_date %}
                  <li>{{ movie.release_date.year }}</li>
                {% endif %}

                <li>
                  {{ movie.genres.all()|join(', ') }}
                </li>

                <li class="movie-card-vote-number">
                  {{ movie.vote_average }}
                </li>
              </ul>
            </section>
          </div>
        {% endfor %}
      </div>

      {% if is_paginated %}
        <div class="pagination pure-text-center">
          {% if page_obj.has_previous() %}
            <a href="{{ url_for('movie_list', page_obj.previous_page_number()) }}">Previous</a>
          {% endif %}

          <span class="page-current">
            {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
          </span>

          {% if page_obj.has_next() %}
            <a href="{{ url_for('movie_list', page_obj.next_page_number()) }}">Next</a>
          {% endif %}
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/tmdb/watchlist.jinja2
{% extends "layouts/application.jinja2" %}

{% from "macros/votes.jinja2" import vote_form with context %}

{% block content %}
  {% for vote in object_list %}
    {%- set movie = vote.movie %}

    <div class="pure-g">
      <div class="pure-u-1-4 box photo-box">
        <a href="{{ url_for('movie', movie.pk) }}">
          <img src="https://image.tmdb.org/t/p/w342{{ movie.poster_path }}"
               alt="{{ movie.title }}">
        </a>
      </div>

      <div class="pure-u-3-4 box">
        <h4>
          <a href="{{ url_for('movie', movie.pk) }}">{{ movie.title }}</a>
          <br>
          <small style="font-style: italic;">{{ movie.original_title }}</small>
        </h4>

        <p>{{ movie.overview_en }}</p>

        {{ vote_form(movie, vote.value) }}
      </div>
    </div>
  {% endfor %}
{% endblock %}